spring.application.name=app

spring.graphql.websocket.path=/graphql
spring.main.web-application-type=reactive

spring.jpa.properties.hibernate.multitenancy=SCHEMA

# Added support for dynamic database type configuration
erp.datasource.type=${DB_TYPE:oracle}
erp.public.schema=${DB_PUBLIC_SCHEMA:ERP_USR}

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${DB_USERNAME:system}
spring.datasource.password=${DB_PASSWORD:testpassword}

spring.datasource.driver-class-name=${DB_DRIVER:oracle.jdbc.OracleDriver}
spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.OracleDialect}
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL:true}

spring.flyway.enabled=true
spring.flyway.placeholders.schema=${erp.public.schema}
spring.flyway.locations=classpath:migration/${erp.datasource.type}/public
spring.flyway.baseline-version=0
spring.flyway.baseline-on-migrate=true

security.jwt.expiration-seconds=${JWT_EXPIRATION:3600}
security.jwt.refresh-expiration-seconds=${JWT_REFRESH_EXPIRATION:604800}
security.jwt.secret=${JWT_SECRET:S0zL4fQr5cYHBJEDKG9u+be0Cbnxt73m0+zaURSoufI=}
bootstrap.api.key=${BOOTSTRAP_API_KEY:}
